name: Blokada 5 for Android (CI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  main_project_module: app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build app
        run: ./gradlew assembleFiveRelease
        
      - name: find apk
        run: |
          findApk=$(find / -name "*.ap" 2>/dev/null)
          echo "apkPath=$findApk" >> $GITHUB_OUTPUT
          echo "$findApk"
        id: findApk

      - name: Upload APK Release - ${{ github.repository }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository }} - APK(s) release generated
          path: ${{ steps.findApk.outputs.apkPath }}
          
      - name: Create tagged release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            *.apk
          tag_name: testApk-build123
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create another tagged release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            ${{ steps.findApk.outputs.apkPath }}
          tag_name: testApk-build987
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
