name: Blokada 5 for Android (CI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  main_project_module: app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build app
        run: ./gradlew assembleFiveRelease

      - name: Generate Tag name for release
        run: |
          echo "tag=build-$(date -I)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        id: release_tag

      - name: Create tagged release 1
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            app/build/outputs/apk/five/release/app-five-release-unsigned.apk
          tag_name: ${{ steps.release_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
