name: Blokada 5 for Android (CI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  main_project_module: app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build app
        run: ./gradlew assembleFiveRelease
        
      - name: Upload APK Release - ${{ github.repository }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository }} - APK(s) release generated
          path: app/build/outputs/apk/five/release/app-five-release-unsigned.apk
        continue-on-error: true
          
      - name: Create tagged release
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            *.apk
          tag_name: testApk-build123a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
